// 8 static blog posts with school-related Unsplash images
const STATIC_BLOGS = [
  { id: "sb-1", title: "Importance of Science Education in Modern Schools", description: "Science education plays a crucial role in developing critical thinking and problem-solving skills among students.", published_date: "2025-01-10", category_id: null, category_name: "Academic", image: "https://images.unsplash.com/photo-1532094349884-543559c5f185?w=500&h=300&fit=crop&auto=format&q=80", isStatic: true },
  { id: "sb-2", title: "How Sports Build Character and Teamwork", description: "Participating in sports helps students develop discipline, leadership, and the spirit of teamwork.", published_date: "2025-02-05", category_id: null, category_name: "Sports", image: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=500&h=300&fit=crop&auto=format&q=80", isStatic: true },
  { id: "sb-3", title: "Celebrating Nepali Culture Through School Programs", description: "Cultural programs at school help students connect with their roots and appreciate the diversity of Nepal.", published_date: "2025-02-20", category_id: null, category_name: "Cultural", image: "https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=500&h=300&fit=crop&auto=format&q=80", isStatic: true },
  { id: "sb-4", title: "Tips for Effective Study Habits", description: "Good study habits are the foundation of academic success. Learn how to study smarter, not harder.", published_date: "2025-03-01", category_id: null, category_name: "Academic", image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500&h=300&fit=crop&auto=format&q=80", isStatic: true },
  { id: "sb-5", title: "Environmental Awareness Among Students", description: "Teaching students about environmental responsibility helps build a greener and more sustainable future.", published_date: "2025-03-15", category_id: null, category_name: "Environment", image: "https://images.unsplash.com/photo-1542601906897-ecd3f7d0e2e3?w=500&h=300&fit=crop&auto=format&q=80", isStatic: true },
  { id: "sb-6", title: "The Role of Arts in Student Development", description: "Art education nurtures creativity, self-expression, and emotional intelligence in young learners.", published_date: "2025-04-02", category_id: null, category_name: "Arts", image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500&h=300&fit=crop&auto=format&q=80", isStatic: true },
  { id: "sb-7", title: "Preparing Students for the Digital Age", description: "Digital literacy is now an essential skill. Schools must equip students with the tools to thrive online.", published_date: "2025-04-18", category_id: null, category_name: "Technology", image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=500&h=300&fit=crop&auto=format&q=80", isStatic: true },
  { id: "sb-8", title: "Graduation: A New Beginning", description: "Graduation marks the end of one chapter and the exciting beginning of another for our students.", published_date: "2025-05-01", category_id: null, category_name: "Ceremony", image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=500&h=300&fit=crop&auto=format&q=80", isStatic: true },
];

export default STATIC_BLOGS;
